### ISSUE TITLE
SW2: Create PHP initial reference implementation

### ISSUE THREAD

**Issue by thill-odi** [openactive/dataset-site-template-php#1]
0.5d

**Comment by nickevansuk** [comment]
Suggest that our PHP library offers two helpers 
- `OpenActiveHelper.renderSimpleDatasetSite`
- `OpenActiveHelper.renderDatasetSite`

This repo should provides an example implementation of these (`index.php` as you suggested).

So this repo could literally be just be something like an `index.php` containing:
```
<?php
echo openActiveEngine.renderSimpleDatasetSite("Our Parks Sessions", "Our Parks",
  true, true, false, false, "https://ourparks.org.uk/openactive", "https://github.com/ourparks/opendata", "Our Parks", "Our Parks - turn up tone up!", "hello@ourparks.org.uk",
  "https://ourparks.org.uk/", "https://ourparks.org.uk/logo.png", "https://ourparks.org.uk/bg.jpg",
  "https://ourparks.org.uk/opendata/", "https://ourparks.org.uk/openbooking/");
?>
```

The library itself should contain something like:

```
function renderSimpleDatasetSite(name, organisationName,
  includeScheduledSessionFeed, includeSessionSeriesFeed, includeEventFeed, includeCourseInstanceFeed,
  datasetSiteUrl, datasetSiteDiscussionUrl, legalEntity, plainTextDescription, email,
  organisationUrl, organisationLogoUrl, backgroundImageUrl, openDataBaseUrl, bookingBaseUrl) {
  // TODO: Create model as per .NET dataset site example, using the PHP model lib we have
  
  renderDatasetSite(model);
}
```

```
function renderDatasetSite(model) {
  // Returns rendered mustache template using model (which is embedded in the package)

}
```

**Comment by thtg88** [comment]
Thanks @nickevansuk I don't think it's super far off from what I've done.

I've already isolated the TemplateRenderer (or what you call Engine in your example) into it's own class, so it'll be just a matter of abstracting a bit more as you described and adding the logic to generate models from that data.

Would you want any form of validation at least so all the fields are included or should we just leave that out?

**Comment by nickevansuk** [comment]
Is it easy to add the validation? How much work roughly do you think? Would be good to ensure that people don't accidentally make broken dataset sites. How would you implement the validation?

**Comment by thtg88** [comment]
Good question - some basic type-checking (sort of a validation) would already be in place when creating OA models i.e. when creating them, an Exception (`InvalidArgumentException` to be precise) will be thrown if not providing an attribute of a supported/valid type.

But technically no validation is performed over required fields, obsolete/deprecated, etc., I think adding it would require some work both around the generator and the model library.

If the type-checking is good with I could implement that easily, otherwise if you need the required+obsolete one, I'll have to get back to you in terms of timescale.

What do you think?

**Comment by thtg88** [comment]
Also @nickevansuk in your sketch above you have `includeCourseInstanceFeed` and `includeEventFeed`, but in the .NET example you have a `FacilityUse` and a `Slot`, do these need to match?
Or should it be:
`includeCourseInstanceFeed` -> `CourseInstance`
`includeEventFeed` -> `Event`

Thanks

**Comment by thtg88** [comment]
Adding agreed answers for clarity:
- Not proceeding with full-blown validation for the time-being due to time constraints, we are happy to rely on the Dataset instantiation type-checking done by the PHP models library for now.
- Moved the flag implementation (`includeXXXXFeed` - specified [here](https://github.com/openactive/dataset-site-template-php/issues/1#issuecomment-545509977)) to a more flexible approach using a `distribution` array parameter, which takes an Enum of `DistributionType`.

**Comment by thtg88** [comment]
PR available for review https://github.com/openactive/dataset-site-template-php/pull/7

**Comment by nickevansuk** [comment]
Completed
